### PR TITLE
chore: deployment target iOS 9 for Xcode 12

### PR DESCRIPTION
**Pull request by lawmicha**
*Issue #, if available:*

On Xcode 12 beta 5, running a sample app works on the simulator and ran into warnings running on the Canvas
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
```

*Description of changes:*
This bumps the iOS deployment target to 9 on all packages < 9, and updates the podspec accordingly

*Related*
_somewhat_ related; the question pretains to SPM but same warning in Xcode  https://developer.apple.com/forums/thread/656616#:~:text=IPHONEOS_DEPLOYMENT_TARGET%20is%20set%20to%208.0,versions%20is%209.0%20to%2014.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by palpatim** [comment]
This is technically a breaking change, since we're updating the minimum supported version of the SDK. Let's discuss and make sure we understand the implications

**Comment by lawmicha** [comment]
i am able to reproduce the carthage build issue in the AWSAuthSDK project

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AWSAuthUIHelper", referenced from:
      objc-class-ref in AWSSignInViewController.o
  "_OBJC_CLASS_$_AWSSignInManager", referenced from:
      objc-class-ref in AWSSignInViewController.o
      objc-class-ref in AWSAuthUIViewController.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by lawmicha** [comment]
- [ ] changelog release for minor version bump
- [ ] doc updates - possible a table indicating SDK/Library support or just an update on SDK docs
- [ ] double check for any iOS "8.0" in case I missed some

**Comment by lawmicha** [comment]
related docs https://github.com/aws-amplify/docs/pull/2348

**Review by palpatim — APPROVED** [review]

**Pull request merged**
