### PR TITLE
Github Optional Shadow Topic Subscription #2039 fix.

### PR DESCRIPTION
**Pull request by karasahinemre**
*Issue #, if available:*

https://github.com/aws-amplify/aws-sdk-ios/issues/2039

*Description of changes:*

Github Optional Shadow Topic Subscription #2039 fix. enableIgnoreDeletes and enableIgnoreRejecteds flags added for decreasing subscribed topic count.

*Check points:*

- [x] Added new tests to cover change, if needed - No need to add new tests.
- [x] All unit tests pass
- [x] All integration tests pass
- [ ] Updated CHANGELOG.md
- [x] Documentation update for the change if required
- [x] PR title conforms to conventional commit style

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by thisisabhash** [comment]
Thank you for raising the PR. We are currently discussing this within our team and will post here with further updates.

**Comment by karasahinemre** [comment]
Hi @thisisabhash,

Any updates?

**Comment by brennanMKE** [comment]
@karasahinemre Hi Emre, could you reach out to us on Discord so we can discuss this?

**Comment by karasahinemre** [comment]
Hi,

We can do this on this Monday if it's okay for you. Can you share your time zone? So, we can find a suitable time for both.

**Comment by karasahinemre** [comment]
Or It would be more convenient if you send a time that suits you and detailed contact information.

**Comment by karasahinemre** [comment]
Hi, 

How can we proceed?

**Comment by karasahinemre** [comment]
Hi,

@brennanMKE, @awsmobilesdk we are waiting for your reply.

Please let me know when you are available.

**Comment by karasahinemre** [comment]
Hi @brennanMKE,

Any updates?

**Comment by brennanMKE** [comment]
@karasahinemre You should have received an email update last week. To summarize, we do not currently support this feature in the SDK so you can use one of the following options.

## Fork SDK

You can fork the SDK and then use it to create a binary framework with our instructions on [Local Development](https://github.com/aws-amplify/aws-sdk-ios-spm/blob/main/README.md#local-development). When there are new releases of the SDK you can rebase and rebuild to get new builds of the binary SDK with each release. If you have a CI/CD system in place you could automate this update with [releases](https://github.com/aws-amplify/aws-sdk-ios/releases) we publish to GitHub using the [GitHub API for Releases](https://docs.github.com/en/rest/reference/releases).

## Experiment with new Swift SDK

You can look into using the [AWS SDK for Swift (Developer Preview)](https://aws.amazon.com/about-aws/whats-new/2021/12/aws-sdk-swift-developer-preview/) which is being prepared for GA release. You can see it produces [many build products for AWS IoT](https://github.com/awslabs/aws-sdk-swift/tree/0.2.1/release) which covers more services and features than the current SDK. In AWSIoTDataPlane you can find `IotDataPlaneClient` has shadow support.

In the short term you could use your forked version and once the new Swift SDK reaches GA release you could migrate to it.

**Pull request closed without merging**
