### PR TITLE
Progress callbacks when app comes into foreground

### PR DESCRIPTION
**Pull request by mrikh**
Added code to resume URLSession Tasks if their state is running when app comes back into foreground (or didBecomeActive). This is a workaround to get progress callbacks.

#1143 

I opened this issue a a couple of years back and mostly forgot about it until recently. The code I added is a workaround endorsed by the people at apple as a solution to the bug in the URLSession class. (https://developer.apple.com/forums/thread/77666)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by palpatim** [comment]
Hi @mrikh and thanks for the PR. As discussed in https://github.com/aws-amplify/aws-sdk-ios/issues/1143, I don't think we need to go to the trouble of adding a lifecycle notification handler. Since we are already loading all tasks from the session, we can just invoke `resume` on the ones in state `NSURLSessionTaskStateRunning`.

**Comment by ptwobrussell** [comment]
@palpatim @mrikh - I'd like to help get this PR get across the line because this is issue is on my shortlist of potential blockers for a new app we are releasing soon that will depend on reliable progress updates for large file uploads.

I've read up on the backlog here - https://github.com/aws-amplify/aws-sdk-ios/issues/1143 - and I'm not quite sure what is the recommended path forward for the fix. I'd be glad to help with a revised PR or some testing, but I'd feel more confident about how to spend the time if I heard back from you first.

**Comment by mrikh** [comment]
@ptwobrussell Basically they don't want to include a life cycle dependency into the SDK. I can understand not wanting to do that from the perspective of developing a SDK but the only potential solution that I have found involves a dependency on it. Since it directly affects the convenience methods offered by the SDK I think it should still be handled by it instead of by the client but that is just my opinion. 

If it is critical to what you are developing, you should be able to handle that on your end. Just get all the current running tasks from `NSURLSession` (should be possible if you and the SDK both use `shared` session, worst case you might have to modify a couple of classes in the SDK to expose that property) and when you get the entered foreground notification, just iterate over all the tasks and call `[task resume]`. You will start getting callbacks for the progress again.

**Comment by ptwobrussell** [comment]
@mrikh Thanks for the clarification (and for surfacing a fix/workaround)!

@mrikh @palpatim In the same way that the consumer of the SDK must opt-in and implement `interceptApplication` in the lifecycle notification `didFinishLaunchingWithOptions`, to handle critical code paths for resumes/restarts, it seems that the consumer of the SDK could be reasonably expected to opt-in here with a utility method exposed by the SDK for this situation. That way, the SDK itself doesn't have a lifecycle dependency but at the same time does make it clear and easy for consumers to handle an underlying bug with some easy copy/paste from the docs. (Otherwise they will have to experience the pain of the bug and track it down the same way we are here...)

In the meanwhile, I may just extend the AWSS3TransferUtility class to do essentially that, per a minor variation of your suggestion, so I'm certainly unblocked. 

Just wanted to offer that additional perspective in case it's helpful for consideration.

**Pull request closed without merging**
