### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by wooj2**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by DongQuanRui — APPROVED** [review]
The Auth SDK one looks good to me

**Comment by lawmicha** [comment]
i think we're missing things from the `develop` branch https://github.com/aws-amplify/aws-sdk-ios/commits/develop

**Comment by lawmicha** [comment]
this PR should also be merged into `develop` branch

**Review by palpatim — DISMISSED** [review]

**Comment by palpatim** [comment]
Did a bit of cleanup during conflict resolution since this PR was a little outdated. Merging.

**Pull request merged**
