### PR TITLE
fix(AWSCore): Add sync control to avoid crash during concurrent credential requests

### PR DESCRIPTION
**Pull request by wxxion**
*Issue #, if available:*
No

*Description of changes:*
The `AWSCredentialsProvider` and `AWSIdentityProvider` have not been implemented to run in multi-threaded environment. Add necessary sync control around `internalCredentials`, `cachedLogins`, `identityId` etc. to fix crashes during concurrent credential requests.

The following is a typical crash stack:
```
Thread 38 Crashed:
0   libobjc.A.dylib                     0x000000018f09e014 objc_msgSend + 20
1   MyApp                               0x00000001063e350c -[AWSCognitoCredentialsProvider credentialsWithCancellationToken:] (AWSCredentialsProvider.m:774)
2   MyApp                               0x00000001066c92dc __30-[AWSAPIGatewayClient invoke:]_block_invoke.115 (AWSAPIGatewayClient.m:0)
3   MyApp                               0x00000001063a46b0 __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke (AWSTask.m:0)
4   MyApp                               0x00000001063a41b0 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke (AWSTask.m:0)
5   MyApp                               0x00000001063ae52c __30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:66)
6   MyApp                               0x00000001063aea40 -[AWSExecutor execute:] (AWSExecutor.m:0)
7   MyApp                               0x00000001063a4018 -[AWSTask continueWithExecutor:block:cancellationToken:] (AWSTask.m:0)
8   MyApp                               0x00000001063a4610 -[AWSTask continueWithExecutor:successBlock:cancellationToken:] (AWSTask.m:0)
9   MyApp                               0x00000001063a4738 -[AWSTask continueWithSuccessBlock:] (AWSTask.m:0)
10  MyApp                               0x00000001066c8944 -[AWSAPIGatewayClient invoke:] (AWSAPIGatewayClient.m:0)
11 ...
```

*Check points:*

- [ N ] Added new tests to cover change, if needed
- [ N ] All unit tests pass (*they can't run in my env before my change*)
- [ N ] All integration tests pass (*they can't run in my env before my change*)
- [ Y ] Updated CHANGELOG.md
- [ N ] Documentation update for the change if required
- [ Y ] PR title conforms to conventional commit style (*I think so although I don't know the details of the required style*)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by royjit — APPROVED** [review]
LGTM

Ran our unit and integration test on AWS iOS SDK and Amplify v1 Auth category without error

**Comment by royjit** [comment]
This code base touches a lot of critical code path of the SDK. We would like to see unit or integ test added that would reproduce this issue and proving that this PR fixes it.

**Comment by wxxion** [comment]
> 

It's a little challenging to reproduce a multithread issue, especially when we need a lot of configuration to make the infected class runnable.
And when I try to add test, I find `AWSCoreTests/AWSCognitoCredentialsProviderTests` doesn't run (not fail, just doesn't run at all). And there are some other failed integration tests. Are they (the integration tests) out of maintenance? (BTW, `AWSCoreUnitTests` are runnable.)

But to understand the fact that a property without sync control may crash is easy:
```
- (void)testMultithreadAssignAndCrash {
    dispatch_queue_t processingQueue = dispatch_queue_create("com.amazon.testqueue", DISPATCH_QUEUE_CONCURRENT);
    dispatch_group_t group = dispatch_group_create();

    __block NSMutableData *data;
    for (int i = 0; i < 1000; i++) {
        dispatch_group_async(group, processingQueue, ^{
            data = [[NSMutableData alloc] init]; // crashes
        });
    }

    dispatch_group_wait(group, DISPATCH_TIME_FOREVER);
}
```
Accordingly, when we have multithreads request for credential and try to set/read/copy credential or identityId, the app may crash if related objects are not sync controlled.

Here is a post from stackoverflow to explain why the crash happens:
https://stackoverflow.com/questions/62994806/why-modifying-mutable-object-in-multi-threading-environment-will-cause-exc-bad-a

**Comment by royjit** [comment]
I am attempting to add the exact behavior you mentioned in the comment - https://github.com/aws-amplify/aws-sdk-ios/pull/4567. Still work in progress

**Review by royjit — DISMISSED** [review]

**Pull request merged**
