### PR TITLE
Only include methods when not targeting Mac Catalyst

### PR DESCRIPTION
**Pull request by colinhumber**
*Issue #, if available:*
#1603 

*Description of changes:*
Include conditional target compilation to exclude methods not available when compiling for macOS Catalyst (previously UIKit for Mac).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by omarqazi** [comment]
Can someone please merge this!

**Comment by samproc** [comment]
Any update on this merge, would be incredibly useful to my project to have this working with a macOS target.

**Comment by fritzgerald** [comment]
I was surprise to see such an important library to no support Catalyst yet.
The fix is so simple why nobody in the core team has review this PR or fix it them self ??

**Comment by gorlov-clearscale** [comment]
@fritzgerald it is not a simple fix. This pull request will **not** work. 

AWS SDK includes pre-compiled binary `libAWSCognitoIdentityProviderASFBinary.a`, which is required for Cognito to work. It will not work either on Catalyst or tvOS due to binary incompatibility.

As a temporary workaround you can make conditional compilation to workaround it but you will loose all the ASF features.

**Comment by fritzgerald** [comment]
> @fritzgerald it is not a simple fix. This pull request will **not** work.
> 
> AWS SDK includes pre-compiled binary `libAWSCognitoIdentityProviderASFBinary.a`, which is required for Cognito to work. It will not work either on Catalyst or tvOS due to binary incompatibility.
> 
> As a temporary workaround you can make conditional compilation to workaround it but you will loose all the ASF features.

Ok thank you i wasn't aware of that, but please enlighten me. It seams to me that `AWSCore` or `AWSS3` for exemple does not have this kind of issue? I might have missed or mis understood
something but why not support Catalyst for each framework when it's possible?

**Comment by gorlov-clearscale** [comment]
@fritzgerald I am not sure why. I am not part of AWS team :) But probably because they have to support as most as they can.

I will try to make pull request with our changes for tvOS/macOS ASAP.

**Comment by ppamorim** [comment]
Please fix this

**Pull request closed without merging**
