### PR TITLE
Added a configurable option to disable & hide the "Create new account" button in the User Pools UI.

### PR DESCRIPTION
**Pull request by jamesingham**
This allows hiding the "Create new account" user sign up button from `AWSAuthUIConfiguration()`.

### CODE REVIEW

**Comment by kvasukib** [comment]
@jamesingham I have updated the branch with the latest changes from master. Waiting for the tests to succeed.

**Comment by jamesingham** [comment]
@kvasukib Thanks, I had been meaning to get around to updating this!

**Comment by kvasukib** [comment]
@jamesingham This change would be part of the next upcoming release. Thank you for the PR.

**Comment by kvasukib** [comment]
@jamesingham This change is released in `2.9.1` release. Thank you for the help!

**Pull request merged**
