### PR TITLE
Fix compile issues when installing AWSS3 with Cocoapods 1.7+ with multiple project generation enabled

### PR DESCRIPTION
**Pull request by colinhumber**
*Description of changes:*
Installing the AWSS3 SDK with Cocoapods 1.7+ with `generate_multiple_pod_projects` enabled caused the frameworks to fail compilation.

`AWSXMLDictionary` was being imported directly within the `AWSS3` project when it exists in `AWSCore`. Fixed this by exposing `AWSXMLDictionary` as a public header and importing the file directly from the `AWSCore` framework.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by palpatim** [comment]
@colinhumber 

Thanks for the PR. Can you point to a small sample app that demonstrates the problem that this is intended to fix? I'm not familiar with the multiple pod projects feature of CocoaPods and how it might  interact. `pod lib lint` succeeds both with and without your change, so I'm unclear what impact this would have for other SDK users.

**Comment by colinhumber** [comment]
@palpatim You bet. I'll get one prepped right away.

**Comment by colinhumber** [comment]
[AWS-CocoaPods-Sample.zip](https://github.com/aws-amplify/aws-sdk-ios/files/3330948/AWS-CocoaPods-Sample.zip)

Building the project as is will fail as it can't find `AWSXMLDictionary.h` in the `AWSS3` project.

The details about that new pod setting is outlined [here](http://blog.cocoapods.org/CocoaPods-1.7.0-beta/). Basically, it splits each pod into it's own project under an umbrella Pods project instead of all pods being in a single master Pods project. This shouldn't impact any other SDK users, as the change is just being more explicit in the importing of files from different frameworks, in this case, importing `AWSXMLDictionary` which is in `AWSCore` into `AWSS3` using the framework import syntax.

**Comment by ReneLindhorst** [comment]
@palpatim #1540 is related and additionally fixes imports in `AWSCognitoIdentityProvider`. It would be awesome if you could have a look at it.

**Comment by palpatim** [comment]
Thanks for the PR and the sample, @colinhumber. I made one change to remove the AWSXMLDictionary import that @hughescr had already put in.

**Comment by colinhumber** [comment]
@palpatim Sounds good!

**Pull request merged**
