### PR TITLE
Fixes threading issues in AWSCredentialsProvider

### PR DESCRIPTION
**Pull request by fer662**
Fixing multiple refreshes going on instead of just one
Fixing thread "cap" being hit by requests waiting on a refresh

### CODE REVIEW

**Comment by kvasukib** [comment]
@fer662 Sorry for the delayed response. Some of the unit tests are failing. Can you check if it's due to the fix from the PR? Your effort is much appreciated!

**Comment by fer662** [comment]
@kvasukib I'm trying to find what test failed but all 3 logs on circleCI say 19 tests passed and 0 failed. Could it have been a fluke in the script? If not let me know what's not passing.

**Comment by fer662** [comment]
@kvasukib seems whatever you merged from master made it pass. I must have branched on a bad spot

**Comment by kvasukib** [comment]
@fer662 Sorry for the trouble. There was an issue in the CircleCI scripts which was fixed by @rohandubal. We are good to go. The next upcoming release will have your changes. Your effort is much appreciated!

**Comment by kvasukib** [comment]
@fer662 This change has been merged in `2.9.1` release. Thank you for the PR!

**Pull request merged**
